### ISSUE TITLE
Issues installing package

### ISSUE THREAD

**Issue by millerbryan** [dwyl/hapi-login-example-postgres#13]
I am very excited to have found this package.  However, I have tried three approaches to installing it and none of them succeed.

1) Download the zip file of the repo.   Unzip, npm install, npm test fails:  **istanbul cover ./node_modules/tape/bin/tape ./test/*.js  | node_modules/tap-spec/bin/cmd.js**

2) npm install /hapi-login-example-postgres --save.  Fails to install package.json file.

3) git clone git@github.com:dwyl/hapi-login-example-postgres.git.  Fails with: **Permission denied (publickey).
fatal: Could not read from remote repository.**

Thanks!

**Comment by nelsonic** [comment]
@millerbryan thank you _very much_ for the feedback!
I have updated the instructions in the readme to `git clone https://github.com/dwyl/hapi-login-example-postgres.git` (_this is the_ **_public**_ _url_ ... _thanks for spotting that!_)

When you attempted to run the tests what _error message_ did you see? (_please paste it_) 
- The Database tables required are: https://github.com/dwyl/hapi-login-example-postgres/blob/master/test/database_setup.sql 
- To set it up, run: `node test/_create_table.test.js`

**Comment by millerbryan** [comment]
I installed Postgres and created a database named test so that should not be an issue.  I added it and the secret key to the config file.

The error from "npm test":

```
> hapi-login-example-postgres@1.0.14 test /home/bmiller/projects/hapi-login-example-postgres-master
> istanbul cover ./node_modules/tape/bin/tape ./test/*.js  | node_modules/tap-spec/bin/cmd.js

No coverage information was collected, exit without writing coverage information
module.js:341
    throw err;
    ^

Error: Cannot find module '../node_modules/hapi-postgres-connection/node_modules/pg/lib/index.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/bmiller/projects/hapi-login-example-postgres-master/test/_create_table.test.js:8:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/bmiller/projects/hapi-login-example-postgres-master/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)


npm ERR! Test failed.  See above for more details.

```

**Comment by nelsonic** [comment]
@millerbryan please try: `npm install` followed by `npm run create` then `npm run dev` for running it on your local machine. let us know if that works. :+1:

**Comment by millerbryan** [comment]
@nelsonic - to be clear, shall I `npm install` the package or `git clone`?

**Comment by millerbryan** [comment]
@nelsonic - I cloned the repo, ran `npm install`, and then `npm run create`.  The following is the error from `npm run create`.

```
[bmiller@jazz hapi-login-example-postgres]$ npm run create

> hapi-login-example-postgres@1.0.14 create /home/bmiller/projects/hapi-login-example-postgres
> node test/_create_table.js

module.js:341
    throw err;
    ^

Error: Cannot find module '../node_modules/hapi-postgres-connection/node_modules/pg/lib/index.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/bmiller/projects/hapi-login-example-postgres/test/_create_table.js:5:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

npm ERR! Linux 3.10.0-327.10.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "create"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! hapi-login-example-postgres@1.0.14 create: `node test/_create_table.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hapi-login-example-postgres@1.0.14 create script 'node test/_create_table.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hapi-login-example-postgres package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node test/_create_table.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hapi-login-example-postgres
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hapi-login-example-postgres
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bmiller/projects/hapi-login-example-postgres/npm-debug.log

```

**Comment by nelsonic** [comment]
@millerbryan please try version `1.0.15` and let us know if you have any more luck. thanks.

**Comment by millerbryan** [comment]
Absolutely.   Many thanks!

**Comment by millerbryan** [comment]
@nelsonic Here are the results for 1.0.15:

```
[bmiller@jazz hapi-login-example-postgres]$ npm test

> hapi-login-example-postgres@1.0.15 test /home/bmiller/projects/hapi-login-example-postgres
> npm run create && istanbul cover ./node_modules/tape/bin/tape ./test/*.test.js  | node_modules/tap-spec/bin/cmd.js


> hapi-login-example-postgres@1.0.15 create /home/bmiller/projects/hapi-login-example-postgres
> node test/_create_table.js

/home/bmiller/projects/hapi-login-example-postgres/node_modules/hapi-postgres-connection/node_modules/pg/lib/index.js
module.js:341
    throw err;
    ^
Error: Cannot find module '/home/bmiller/projects/hapi-login-example-postgres/node_modules/hapi-postgres-connection/node_modules/pg/lib/index.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/bmiller/projects/hapi-login-example-postgres/test/_create_table.js:7:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

npm ERR! Linux 3.10.0-327.10.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "create"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! hapi-login-example-postgres@1.0.15 create: `node test/_create_table.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hapi-login-example-postgres@1.0.15 create script 'node test/_create_table.js'.

```

If the field names and types are listed I will create them and run the app.  It may be that evertyhing is good with the exception of the "create table" test.

**Comment by soixantseize** [comment]
I am getting the same error when running npm test.

**Comment by nelsonic** [comment]
@millerbryan + @ReketeBravo please try again. I've removed the line that was causing the error in both your cases. 
please let me know how you get on. thanks!

**Comment by millerbryan** [comment]
@ReketeBravo You appear to have made more progress than I.  I never see the SQL insert command.  What is your sequence of installation?

**Comment by soixantseize** [comment]
**@nelsonic** Everything is Awesome, thank you so much!

**@millerbryan**  I am using a Ubuntu 14.04 VM, make sure your database_url is correct. Also, always give **postgres** user a **password**

**Comment by millerbryan** [comment]
@nelsonic The test is running tickety-boo now until it fails to authenticate.  I suspect I need to add a password to my config.env file.  I am not a Postgres guy so I'll need to dig a bit deeper.

Thank you for everything!

**Comment by nelsonic** [comment]
@millerbryan + @ReketeBravo please :star: this repo if you have found it _useful_ to let others know about ...
and @millerbryan please close the issue to confirm everything is working as expected. 
(_feel free to open other issues/questions if you need help with anything else_...)
