### ISSUE TITLE
send verification email to people who have registered?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-login-example-postgres#22]
Should we send a _real_ verification email to people who have registered?

**Comment by alexdrans** [comment]
I don't see why not. Personally I'm a fan of complete examples, but (as I mentioned in the other issue) it does add complexity. What are the goals here? Easy to understand examples, or proper implementations?

**Comment by nelsonic** [comment]
@alexdrans good question. I think we have a _decent_ example of sending email from Node/Hapi apps over at: https://github.com/dwyl/sendemail
This example was _specifically_ to be a _gentle_ intro to using PostgreSQL with Hapi...

**Comment by alexdrans** [comment]
@nelsonic In that case, I would say keep this example pure. I'm certainly interested in putting together some 'real world' examples though which tie together a few dwyl examples. But that's for another day..

**Comment by nelsonic** [comment]
Those "_real world_" examples will be released _very_ soon... :wink:
For now I think I'm going to _close_ this issue. 👍 
Hope you're having a great weekend! ☺️
