### ISSUE TITLE
can we have a generic database error handler?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-login-example-postgres#23]
`test/error_handler.tests.js` containing:

``` js
var test = require('tape');
var error_handler = require('../lib/error_handler');

test('/db/error-handler-tests.js: error_handler fail condition', function(t) {
  var msg = 'Your Custom (Optional) Error Message';
  var res = error_handler('boom', msg);
  t.equal(res, msg);
  t.end();
});

test('/db/error-handler-tests.js: error_handler no error condition', function(t) {
  var res = error_handler(null);
  t.equal(res, false);
  t.end();
});
```

**Comment by nelsonic** [comment]
Might use https://github.com/dwyl/hapi-error for this... @alexdrans did you have a look at it? 😉

**Comment by alexdrans** [comment]
@nelsonic I've had a look, but a) I don't immediately know how to implement this and b) I'm very short on time. If this issue can stay open for a while, I can implement it, otherwise I'll have to help out elsewhere instead :cry:
