### ISSUE TITLE
Could we integrate Redis sessions in this example?

### ISSUE THREAD

**Issue by alexdrans** [dwyl/hapi-login-example-postgres#25]
I know there's already an example of using Redis with sessions, but could we also integrate it here? It's a very good practice and it isn't particularly complicated to implement. The drawback of course is including too many new concepts that aren't necessary to explain the core concept.

**Comment by nelsonic** [comment]
Yeah, typically a project that's already using a `SQL` database will only invest time in "_performance optimisation_" when they are _sure_ that its their database that is the bottleneck. In the case of _sessions_ for this _example_ app (_or the 3 client apps we are building that use Postgres_) the session lookup query takes 40ms round-trip to the PostreSQL Server (_the sessions table is indexed and cached_).

Its best to only build something when you _need_ it. but you're _right_ it would be _easy_ to implement this borrowing the code from [hapi-auth-jwt2-example](https://github.com/dwyl/hapi-auth-jwt2-example/blob/4c8501976867171a3797b8a23141f4d1df4aae46/index.js#L25) ... 👍

**Comment by nelsonic** [comment]
@alexdrans give it a go for practice. 
Write a _perf_ test where you login and access an `auth:required` endpoint 1000 times and see how much faster the requests are when using Redis vs. PostgreSQL. 
Paste the results into this issue. 🚀
